### ISSUE TITLE
关于其它平台视频解析

### ISSUE THREAD

**Issue by mmdg1314-prog** [K12f/BlueCatKoKo#2]
老大，后期会更新快手视频的下载吗？批不批量无所谓，单个视频解析能支持就挺好了。可以增加打赏功能，加油创作下去！

**Comment by K12f** [comment]
哈哈，有想添加小红书的，想批判一下妹子😎，快手我有空研究一下

**Comment by K12f** [comment]
@mmdg1314-prog 新版本已支持快手
