### ISSUE TITLE
已赞助 goon

### ISSUE THREAD

**Issue by wolf777a** [K12f/BlueCatKoKo#5]
我正在学习WPF相关内容，可以交流一下嘛 😊😊😊，找不到您的联系方式

**Comment by K12f** [comment]
哈哈，谢谢。有啥问题可以直接在这里问我哦

**Comment by wolf777a** [comment]
感觉WPF国内视频资料好少，不会像java资料那么多，您平时是如何学习的呢，目前工作是和WPF相关的嘛
