### ISSUE TITLE
【BUG】文件名称不符合Windows文件名称格式

### ISSUE THREAD

**Issue by sillsun** [K12f/BlueCatKoKo#9]
HomeViewModel.cs

private async Task DownloadAll() 

由于当前代码是最直接使用Data.Desc（视频描述）中很可能存在非法的字符导致下载保存失败（显示下载成功，但是找不到对应文件）

解决方法：
      将文件名称进行预处理，保证文件名称合法。

**Comment by K12f** [comment]
哪个视频，我试试。这个问题确实有的

**Comment by K12f** [comment]
新版已经处理了，你试试
